server:
  port: ${SERVER_PORT}

database:
  host: ${DB_HOST}
  port: ${DB_PORT}
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  name: ${DB_NAME}

jwt:
  secret: ${JWT_SECRET}
  access_token_duration: ${ACCESS_TOKEN_DURATION}
  refresh_token_duration: ${REFRESH_TOKEN_DURATION}

r2:
  account_id: ${R2_ACCOUNT_ID}
  access_key_id: ${R2_ACCESS_KEY_ID}
  access_key_secret: ${R2_ACCESS_KEY_SECRET}
  bucket_name: ${R2_BUCKET_NAME} 